### ISSUE TITLE
Flattening Errors

### ISSUE THREAD

**Issue by martyall** [lucasdicioccio/http2-client-grpc#14]
There's a pretty deep nesting of `Either`s behind the simplest rpc response. Using `rawUnary` and running down to `IO` produces something like

```haskell
Either ClientError (
  (Either TooMuchConcurrency 
    (Either ErrorCode 
      (CIHeaderList, Maybe CIHeaderList, (Either String a))
    )
  )
)
```

meaning accessing the response of type `a` requires a pretty deep case statement. Is there some way to flatten this out a bit. I don't know enough about the protocol to make a real suggestion, it's just been a pain point for me.

I see the comment [here](https://github.com/lucasdicioccio/http2-client-grpc/blob/master/src/Network/GRPC/Client.hs#L111)
>  A future version of the library will have a proper data structure with properly named-fields on the reply object.

**Comment by lucasdicioccio** [comment]
Hi thanks for the report! this is useful feedback.

I sort of inherited the http2-client way of doing things -- which sucks but I wanted it to have reasonably small dependencies. 
Since this package is much heavier and we're using proto-lens there exists some helpers using lens in the `Network.GRPC.Client.Helpers` module in the form of `unaryOutput = _Right . _Right . _3 . _Right` which you can use with the `preview` function.

If you're not familiar with lens you'll be missing out on a lot of `proto-lens` love (idk. what is a good tutorial these days but the 'lens over tea' is definitely a big reference).

Maybe we should also peel the `Either ClientError` these days.


Tell me if it answers your problem well, and if does so, please submit a documentation patch to increase the visibility of the Helpers module 🙏 .

**Comment by lucasdicioccio** [comment]
We are migrating at https://github.com/haskell-grpc-native/http2-grpc-haskell/issues/5 .
